name: Publish to Maven Central

on:
  push:
    branches:
      - master
    tags:
      - 'v*'  # e.g. v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private.key
          gpg --batch --import private.key
          gpg --list-secret-keys

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21  # or 17
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          cache: maven

      - name: Create minimal settings.xml (if needed)
        run: |
          mkdir -p ~/.m2
          echo "<settings>" > ~/.m2/settings.xml
          echo "  <servers>" >> ~/.m2/settings.xml
          echo "    <server>" >> ~/.m2/settings.xml
          echo "      <id>ossrh</id>" >> ~/.m2/settings.xml
          echo "      <username>${{ secrets.OSSRH_USERNAME }}</username>" >> ~/.m2/settings.xml
          echo "      <password>${{ secrets.OSSRH_PASSWORD }}</password>" >> ~/.m2/settings.xml
          echo "    </server>" >> ~/.m2/settings.xml
          echo "  </servers>" >> ~/.m2/settings.xml
          echo "</settings>" >> ~/.m2/settings.xml

      - name: Deploy to OSSRH (manual close/release from UI)
        run: |
          mvn clean deploy -P release -DskipTests -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
