name: Publish to Maven Central

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import GPG Key (manual debug step)
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > gpg.key
          gpg --batch --import gpg.key

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Deploy to Maven Central
        run: mvn clean deploy -P release -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" -DskipTests
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
